export const themes = {
  light: {
    background: '#FAFAF8',
    card: '#FFFFFF',
    cardBorder: '#ECECEA',
    text: '#1A1A1A',
    textSecondary: '#7A7A72',
    textTertiary: '#AEAEA6',
    tileBg: '#F0F0EE',
    tileSelected: '#1A1A1A',
    tileSelectedText: '#FFFFFF',
    tileSelectedBorder: 'transparent',
    tileHintBg: '#FEF3C7',
    tileHintBorder: '#F59E0B',
    submitBg: '#1A1A1A',
    submitText: '#FFFFFF',
    submitDisabledBg: '#D5D5D3',
    submitDisabledText: '#A0A09A',
    buttonBorder: '#DDDDD8',
    dailyCardBg: '#1A1A1A',
    dailyCardText: '#FFFFFF',
    dailyCardSubtext: 'rgba(255,255,255,0.55)',
    progressTrack: '#E8E8E6',
    lifeDot: '#E24B4A',
    lifeDotEmpty: '#E0E0DE',
    divider: '#ECECEA',
    toastBg: '#1A1A1A',
    toastText: '#FFFFFF',
    accentBg: '#FFF3ED',
    hintBadgeBg: '#FFF3ED',
    hintBadgeEmptyBg: '#F0F0EE',
    hintBadgeEmptyText: '#AEAEA6',
    warningBg: '#FAEEDA',
    warningText: '#92400E',
    successBg: '#E1F5EE',
    errorBg: '#FCEBEB',
    settingsGroupBg: '#FFFFFF',
    priceBtnBg: '#F0F0EE',
    statusBarStyle: 'dark' as const,
  },
  dark: {
    background: '#0C0C0E',
    card: '#1A1A1E',
    cardBorder: '#2A2A2E',
    text: '#F5F5F5',
    textSecondary: '#8E8E93',
    textTertiary: '#636366',
    tileBg: '#1A1A1E',
    tileSelected: '#FFFFFF',
    tileSelectedText: '#000000',
    tileSelectedBorder: '#444448',
    tileHintBg: '#2D2A1A',
    tileHintBorder: '#F59E0B',
    submitBg: '#FFFFFF',
    submitText: '#000000',
    submitDisabledBg: '#333338',
    submitDisabledText: '#636366',
    buttonBorder: '#3A3A3E',
    dailyCardBg: '#FFFFFF',
    dailyCardText: '#000000',
    dailyCardSubtext: 'rgba(0,0,0,0.5)',
    progressTrack: '#2A2A2E',
    lifeDot: '#FF6B6B',
    lifeDotEmpty: '#2A2A2E',
    divider: '#2A2A2E',
    toastBg: '#F5F5F5',
    toastText: '#0C0C0E',
    accentBg: '#2D1A10',
    hintBadgeBg: '#2D1A10',
    hintBadgeEmptyBg: '#1A1A1E',
    hintBadgeEmptyText: '#636366',
    warningBg: '#2D2410',
    warningText: '#F59E0B',
    successBg: '#0D2818',
    errorBg: '#2D1010',
    settingsGroupBg: '#1A1A1E',
    priceBtnBg: '#2A2A2E',
    statusBarStyle: 'light' as const,
  },
} as const;

export type ThemeColors = {
  [K in keyof typeof themes.light]: string;
};
export type ThemeMode = 'light' | 'dark' | 'system';

export const shared = {
  category1: '#7B68EE',
  category2: '#2EAE7B',
  category3: '#E8723A',
  category4: '#3B82F6',
  accent: '#E8723A',
  accentLight: '#FFF3ED',
  accentLightDark: '#2D1A10',
  success: '#2EAE7B',
  error: '#E24B4A',
  warning: '#D97706',
  categoryTextPrimary: 'rgba(255,255,255,0.95)',
  categoryTextSecondary: 'rgba(255,255,255,0.7)',
} as const;

export const categoryColors = [
  shared.category1,
  shared.category2,
  shared.category3,
  shared.category4,
] as const;

export const categoryLightColors = [
  '#EEEDFE',
  '#E1F5EE',
  '#FAECE7',
  '#E6F1FB',
] as const;

export const categoryDarkColors = [
  '#4A3FB0',
  '#1B7A53',
  '#B85425',
  '#2563EB',
] as const;
